server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      encoding: utf-8
      data-locations:
        - classpath:db/data.sql
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false
mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.mybatis: DEBUG